### ISSUE TITLE
License

### ISSUE THREAD

**Issue by NoxiousPluK** [Kermalis/SudokuSolver#1]
Hi!

What is the license for this project? I was looking to perhaps use some of your code in a project of my own, but there is no license specified.

Thanks in advance!

**Comment by Kermalis** [comment]
I made this purely for fun so there is no license, meaning you are free to copy/use it wherever you want without credit, although credit is nice. There are already many people using this for many purposes as well.

**Comment by NoxiousPluK** [comment]
Thank you for your quick response!
When you make a creative work (which includes code), the work is under exclusive copyright by default.

Based on what you wrote above I will assume (and suggest) the zlib license:
https://en.wikipedia.org/wiki/Zlib_License

**Comment by Kermalis** [comment]
Done
