### ISSUE TITLE
Compile problems

### ISSUE THREAD

**Issue by jeb1248** [Kermalis/SudokuSolver#3]
Just curious as to how you compiled the program.  I've tried in Visual Studio 2017 and 2019 and it errored-out trying to open MainWindow.cs and SudokuBoard.cs.  I'm an intermediate-level programmer trying to review the code to learn new techniques.

**Comment by Kermalis** [comment]
I always used Visual Studio 2019, what's the error you're getting?

**Comment by jeb1248** [comment]
WOW!  Sorry...I just wasn't expecting such a rapid response.  And Thank You.
I get this when I try to open MainWindow.cs:
[image: image.png]
When I click on "Go to code" it takes me to MainWindow.Design.cs line 61:
            this.splitContainer1.Panel1.Controls.Add(this.sudokuBoard);

When I open SudokuBoard.cs I get:
[image: image.png]
And "Go to code" it takes me to  SudokuBoard.Design.cs line 45:
            LostFocus += (sender, e) => SudokuBoard_KeyPress(sender, null);

If I can send any more messages please let me know.
I probably just have something set up wrong.  I hope it's a simple
problem.  I thought it's probably easier to ask the question up front than
spending time running in circles and asking later anyway.

Thanks for you attention,
John

**Comment by Kermalis** [comment]
Your images didn't upload, but for the forms I think I stopped designing them with the designer and just made them in code. The designers won't know how to deal with it since it's not the Microsoft format anymore

**Comment by jeb1248** [comment]
Sorry to keep bothering you.  From your last email I thought maybe there
might be files missing.  So  I deleted all of the files I had downloaded
from GitHub, re-downloaded the .zip and tried again in VS 2019 and still
got the same errors. You said in your email that the images were in code.
The only way I've set up forms has been through the Designer and images
through references.  Does that mean I need to add a reference to relieve
the designer of errors?  If that's the case, where would I find the files
to use as references?  Or is there some other tactic you would suggest?
Thanks again,
John

**Comment by Kermalis** [comment]
I meant the images from your reply here were missing, I just see this:

![image](https://user-images.githubusercontent.com/29823718/82699323-6d0fa700-9c3a-11ea-8888-43458f931c91.png)

But if it's about trying to open the SudokuBoard and MainWindow in the designer, I think it's normal since they're not meant to be opened there

**Comment by jeb1248** [comment]
I compiled and ran the program without invoking the Designer and all worked
OK.  I started looking through the code and I can tell there's a lot of
techniques that I can learn from this.  Thanks again for your patience.

John

**Comment by Kermalis** [comment]
No problem, glad you got it working :)

**Comment by jeb1248** [comment]
Hi.  Thanks to you I'm having a great time.  I've been reading/stepping
through the code of your Sudoku program and have learned a lot.  I thought
I was at least an "Advanced" C# programmer, probably because some of the
programs I've written were quite extensive (e.g. a Job-Cost-Estimation
program and a full Inventory-Management program using a large database).
But now I'd have to say I'm probably an Intermediate C# programmer.  I
think some of that stems from a long history of coding in 'C', which can be
limiting, and some from laziness.  I "know" a lot about C#, meaning I've
read a bunch about it.  But there's a fair distance between having seen it
referred to in print and applying it in code.  In looking at your program
I'm getting a much better idea of how to apply those techniques.  And
that's why I'm thanking you for putting it out on GitHub.
Cheers,
John Burke

**Comment by Kermalis** [comment]
@jeb1248 no problem, glad to have people looking at it. I wrote it when I was just getting back into coding, so it's not the cleanest and it's not how you'd want to code something speedy. The things I've been working on more recently are a lot better in every aspect, if you're interested you can check out https://github.com/Kermalis/PokemonBattleEngine since it's my main focus now
